### ISSUE TITLE
Multiple learning rates like AUTOMATIC1111s Textual Inversion: "0.005:100, 1e-3:1000, 1e-5"

### ISSUE THREAD

**Issue by blackmagic24** [ShivamShrirao/diffusers#105]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Textual-Inversion
...
It's possible to specify multiple learning rates in this setting using the following syntax: 0.005:100, 1e-3:1000, 1e-5 - this will train with lr of 0.005 for first 100 steps, then 1e-3 until 1000 steps, then 1e-5 until the end.
...
Thanx

**Comment by ShivamShrirao** [comment]
@blackmagic24 currently the following learning rate schedulers are supported.
```
LINEAR
COSINE
COSINE_WITH_RESTARTS
POLYNOMIAL
CONSTANT
CONSTANT_WITH_WARMUP
```
More info here for warmup steps.
https://github.com/ShivamShrirao/diffusers/blob/main/examples/dreambooth/train_dreambooth.py#L630
