### ISSUE TITLE
More than 12gb video memory with --gradient_checkpointing  and --use_8bit_adam

### ISSUE THREAD

**Issue by wodsoe** [ShivamShrirao/diffusers#106]
https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb

test colab notebook

![1](https://user-images.githubusercontent.com/40934627/199043705-c7d16cda-46ea-45ed-8e5c-f3ce7816f338.png)
![2](https://user-images.githubusercontent.com/40934627/199043736-699da1c0-2ced-4173-a47a-fbc3bc112ee1.png)

How to reduce VRAM usage to 9.92 GB?

**Comment by rexroth0619** [comment]
You may have to disable --train_text_encoder. Sucks I know, also looking for a way to include that on a 3080Ti

**Comment by ShivamShrirao** [comment]
@wodsoe @rexroth0619 Currently text encoder training requires 12 GB VRAM. It is showing bit above 12 GB here but it works in 12 GB vram gpus.

**Comment by wodsoe** [comment]
Thank you! It's OK.
