### ISSUE TITLE
Cant convert NovelAI .ckpt to diffusion format

### ISSUE THREAD

**Issue by DoubleCake** [ShivamShrirao/diffusers#107]
### Describe the bug

 Got unexpected key(s) in state_dict  by using convert script to convert NovelAL model to diffusion format.

### Reproduction
this is my commond line input:

python  ./scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path=./examples/dreambooth/localModels/nd_final.ckpt --scheduler_type=ddim --dump_path=./localModel/nd_final
The nd_final.ckpt is a novelAL Model
###
It is appreciated for answering my question in your busy tim

_No response_

### Logs

```shell
Unexpected key(s) in state_dict: "embeddings.position_ids", "embeddings.token_embedding.weight", "embeddings.position_embedding.weight", "encoder.layers.0.self_attn.k_proj.weight", "encoder.layers.0.self_attn.k_proj.bias", "encoder.layers.0.self_attn.v_proj.weight", "encoder.layers.0.self_attn.v_proj.bias",
```

### System Info

windows-wsll

**Comment by DoubleCake** [comment]
https://drive.google.com/drive/folders/1vOaFitkJ1MOig6VD-ubnQkg239Dzpn15?usp=share_link

**Comment by Omegastick** [comment]
Thanks for sharing the converted model. How did you get it working?

**Comment by DoubleCake** [comment]
> 
I downloaded the model and I converted it to ckpt. The test results are consistent with the original NovelAI model. I need this model stable diffusion format to train DreamBooth, so when I find this link, I close the problem

>
