### ISSUE TITLE
NO OPTION to UPLOAD CLASS IMAGES MYSELF?

### ISSUE THREAD

**Issue by LIQUIDMIND111** [ShivamShrirao/diffusers#113]
### Describe the bug

To wait for 15 generated images is the same as uploading 100 ALREADY class images i have BETTER QUALITY than the ones generating...... ??? no way whatsoever/?

### System Info

Dreambooth collab

**Comment by ShivamShrirao** [comment]
Put them in `class_data_dir` . Upload with the file manager on side bar.

**Comment by LIQUIDMIND111** [comment]
oh ok thanks.
