### ISSUE TITLE
Models created via the DreamBooth_Stable_Diffusion colab always fp16 regardless of selection

### ISSUE THREAD

**Issue by TheMundaneDave** [ShivamShrirao/diffusers#124]
### Describe the bug

For the last few days, any model I crate from the colab (always current copied form the day of use) generate 2GB ckpt files regardless of the the fp16 selection chosen under Convert weights to ckpt to use in web UIs like AUTOMATIC1111

### Reproduction

Generate a model with the fp16 selection cleared

### System Info

using the colab at https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb

**Comment by ProGamerGov** [comment]
@ShivamShrirao I just ran into this error as well.

**Comment by ProGamerGov** [comment]
@TheMundaneDave Use the Dreambooth script from this commit for now as it doesn't have the bug: https://github.com/ShivamShrirao/diffusers/commit/c28895aedaa5d9316e42a380723ea472cf6a0e8e

**Comment by ProGamerGov** [comment]
Looks like a new commit was made, which partially resolves the issue: https://github.com/ShivamShrirao/diffusers/commit/389d7461cb44992aa32adc05d6a87d473ff01250


However, it still defaults to floating point 16 in the training loop:

```
torch_dtype = torch.float16 if accelerator.device.type == "cuda" else torch.float32
```

And in the model saving section:

```
torch_dtype=torch.float16,
```

**Comment by ShivamShrirao** [comment]
The first line is in class image generation. Shouldn't really affect your results.

In saving section that is only applied to parts that are loaded. Unet and text encoder will be in fp32. You should get full 4gb ckpt files now.
Also remove fp16 from `--revision` if u want fp32.
