### ISSUE TITLE
DreamBooth training image resizing can produce harmful artifacts, as antialiasing is not enabled

### ISSUE THREAD

**Issue by ProGamerGov** [ShivamShrirao/diffusers#126]
### Describe the bug

In the DreamBooth training code, this line

```
transforms.Resize(size, interpolation=transforms.InterpolationMode.BILINEAR),
```

The artifacts that can be produced by resizing will harm the training.

Source: https://github.com/ShivamShrirao/diffusers/blob/main/examples/dreambooth/train_dreambooth.py

It should include the antialiasing argument:

```
transforms.Resize(size, interpolation=transforms.InterpolationMode.BILINEAR, antialias=True),
```

https://pytorch.org/vision/stable/generated/torchvision.transforms.Resize.html#torchvision.transforms.Resize

### System Info

N/A

**Comment by ShivamShrirao** [comment]
We are resizing PIL images which are always resized with antialiasing. This flag is not needed.
