### ISSUE TITLE
xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by cedro3** [ShivamShrirao/diffusers#152]
### Describe the bug

In DreamBooth_Stable_Diffusion.ipynb, Install xformers from precompiled wheel gives error ERROR: xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.

### Reproduction

%pip install -q https://github.com/metrolobo/xformers_wheels/releases/download/1d31a3ac_various_6/xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl

### Logs

```shell
ERROR: xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
```

### System Info

google colab

**Comment by paulmbw** [comment]
I'm also seeing this error

**Comment by paulmbw** [comment]
@ShivamShrirao are you already looking into this?

**Comment by ShivamShrirao** [comment]
Oh I wasn't. But just realised colab updated to python 3.8. Will have to update the wheels.

**Comment by paulklen** [comment]
> Oh I wasn't. But just realised colab updated to python 3.8. Will have to update the wheels.

Awesome, would be great if this is done soon (happy to contribute as well if you can direct me what needs changing)

**Comment by cedro3** [comment]
Hi
I’m looking forward to you making a whl for python3.8. Thank you so much.

iPhoneから送信

**Comment by jslegers** [comment]
I also logged this @ https://github.com/metrolobo/xformers_wheels/issues/2.

**Comment by relaxedray** [comment]
just use this one of the old one
%pip install -q https://github.com/OMGhozlan/xformers_colab/releases/download/1.0.0/xformers-0.0.15.dev0+cu11.2-cp38-cp38-linux_x86_64.whl
seems to have worked for me

**Comment by ShivamShrirao** [comment]
FIxed in ecf24b5ece63b819b351cdb4b1a24910aa85b757

**Comment by metrolobo** [comment]
@ShivamShrirao Btw the Nvidia site lists the P100 as compute version 6.0 https://developer.nvidia.com/cuda-gpus

I think that gave people issues the last time on P100 so one with 6.0 included in the ARCH arg was required but it has been a while so I'm not totally sure anymore.

If that is the case there's one with 6.0 here if you want:  https://github.com/metrolobo/xformers_wheels/releases

**Comment by ShivamShrirao** [comment]
@metrolobo , Thanks, will update.
