### ISSUE TITLE
Is there any instruction for using inpainting for dreambooth?

### ISSUE THREAD

**Issue by log901108** [ShivamShrirao/diffusers#172]
**Is your feature request related to a problem? Please describe.**

I am a student who is struggling to working on dreambooth.

I've  just finished to make app give dreambooth result by train_dreambooth.py and inference script

now I'm wonder do I need to train model again through train_inpainting_dreamboth.py or not for inpainting.
or just any other way to use inpainting inference

I am stucked here for one month because there is no instruction for inpainting anywhere..

anybody help me? give a instruction or example to use inpainting by dreambooth

**Comment by i-amgeek** [comment]
Hey @log901108 , did you find instructions to use inpainting dreambooth?
