### ISSUE TITLE
Is the train_dreambooth.py only trains the VAE part or also including diffusers models?

### ISSUE THREAD

**Issue by wyang22** [ShivamShrirao/diffusers#198]
After training, only there are some scheduler, VAE, U net and Text related folders & bin files saved, and there is no bin file generated in the scheduler folder, so want to confirm this, thanks

**Comment by ShivamShrirao** [comment]
It trains the unet and optionally the text encoder. VAE isn't trained in this and scheduler is basically an algorithm, not a model, it is not/can't be trained.

**Comment by wyang22** [comment]
How can I config to train the text encoder?
Are the Unet and the text encoder can represent the whole stable diffusion model? If not, will the model capacity too small? Thanks
