### ISSUE TITLE
Support for multiple fine-tuned concepts & classes on one model with Dreambooth

### ISSUE THREAD

**Issue by jslegers** [ShivamShrirao/diffusers#21]
**Is your feature request related to a problem? Please describe.**
I'd like to add multiple people and/or objects to a single model and finetune my model for that. For example, I'd like to add an entire family, together with their pets and their car, and this with as little degradation of my overall model as humanly possible.

**Describe the solution you'd like**
I'd like to add multiple people and/or objects to a model and finetune my model with a minimal amount of degradation.

**Describe alternatives you've considered**
I've been tinkering around with different classes and concepts, but thusfar any attempt to use a different class or concept thusfar always lead to extreme degradation. 

**Additional context**
Apparently someone already forked [JoePenna/Dreambooth-Stable-Diffusion](https://github.com/JoePenna/Dreambooth-Stable-Diffusion) at [kanewallmann/Dreambooth-Stable-Diffusion](https://github.com/kanewallmann/Dreambooth-Stable-Diffusion) to add support for multiple concepts & classes on one model. However, that version of Dreambooth SD requires at least 24GB VRAM, which means I can't run it on either my machine or a free Google Colab, which is what I've been using so far.

Related :

- https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/51
- https://github.com/huggingface/diffusers/issues/752

**Comment by ShivamShrirao** [comment]
@jslegers Yeah nice suggestion, I was also looking into it, Just haven't done enough testing yet to see how well it works.

Or I might just update it with an option first so that people can try it atleast without ruining the current results.

**Comment by IdiotSandwichTheThird** [comment]
@ShivamShrirao if you do add it, please make it use the caption for each image from a .txt with the same name, since it's a lot of easier creating that with automatic's blip captioning, rather than manually naming each image.

**Comment by ShivamShrirao** [comment]
@IdiotSandwichTheThird It has been added now. 351f3b6206f0453706346fd34a337cdf6ac6ef07

Yes, it makes use of a json to get names and class.
