### ISSUE TITLE
Generating config yaml from DreamBooth model based on SD v2.1 (along with ckpt)

### ISSUE THREAD

**Issue by sooolee** [ShivamShrirao/diffusers#213]
Hello,

I trained a DreamBooth model based on SD v2.1. To use it in AUTOMATIC 1111, need a configuration yaml file along with ckpt. Using Colab, I generated the ckpt but can't get yaml from the model output (weights). Am I missing something? Could you please help me on this?   Thanks!!

**Comment by wyang22** [comment]
Same request here, how to get the ckpt or pth file trained after local training? Looks like they are all bin files, thanks
