### ISSUE TITLE
Specifying a gdrive dir for instance pics upload

### ISSUE THREAD

**Issue by got2bi** [ShivamShrirao/diffusers#22]
It could save a lot of time if we can use a folder in our gdrive account instead of generating pics for the class.

**Comment by Twizzes** [comment]
You can do this if you edit the code of the relevant colab cells - I agree it would be nice to be able to do this more easily, though

**Comment by ShivamShrirao** [comment]
@got2bi as @Twizzes said you can do this by overwriting the CLASS_DIR variable with path to your class pics.

Will try to make it more user friendly. Until then PRs are also welcome as I haven't been able to put much time in UI of the colab lately.
