### ISSUE TITLE
TypeError: Accelerator.__init__() got an unexpected keyword argument  'logging_dir'

### ISSUE THREAD

**Issue by tumielsexshop** [ShivamShrirao/diffusers#239]
### Describe the bug

TypeError: Accelerator.__init__() got an unexpected keyword argument 
'logging_dir'

### Reproduction

2023-06-07 23:22:05.427601: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/train_dreambooth.py:869 in <module>                                 │
│                                                                              │
│   866                                                                        │
│   867 if __name__ == "__main__":                                             │
│   868 │   args = parse_args()                                                │
│ ❱ 869 │   main(args)                                                         │
│   870                                                                        │
│                                                                              │
│ /content/train_dreambooth.py:425 in main                                     │
│                                                                              │
│   422 def main(args):                                                        │
│   423 │   logging_dir = Path(args.output_dir, "0", args.logging_dir)         │
│   424 │                                                                      │
│ ❱ 425 │   accelerator = Accelerator(                                         │
│   426 │   │   gradient_accumulation_steps=args.gradient_accumulation_steps,  │
│   427 │   │   mixed_precision=args.mixed_precision,                          │
│   428 │   │   log_with="tensorboard",                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: Accelerator.__init__() got an unexpected keyword argument 
'logging_dir'

### System Info

??

**Comment by imccainiao** [comment]
Also have the same problem.

**Comment by winstoncesar** [comment]
I have the same problem too

**Comment by NatalieHanzhina** [comment]
From the official huggingface repo's [issue](https://github.com/huggingface/accelerate/issues/1559):

This is now project_dir (**not logging_dir**), and you should have been seeing warnings of it being deprecated for the last few accelerate versions.

**Comment by imccainiao** [comment]
> From the official huggingface repo's [issue](https://github.com/huggingface/accelerate/issues/1559):
> 
> This is now project_dir (**not logging_dir**), and you should have been seeing warnings of it being deprecated for the last few accelerate versions.

thanks
after i replace logging_dir by project_dir in file "train_dreambooth.py" ,it works

**Comment by NatalieHanzhina** [comment]
@ShivamShrirao I made a PR

**Comment by SashaAlexandra22** [comment]
> 



> > From the official huggingface repo's [issue](https://github.com/huggingface/accelerate/issues/1559):
> > This is now project_dir (**not logging_dir**), and you should have been seeing warnings of it being deprecated for the last few accelerate versions.
> 
> thanks after i replace logging_dir by project_dir in file "train_dreambooth.py" ,it works

Thank you, @imccainiao ! I`m trying to replace logging_dir to project_dir and it doesn`t work. Can you be more specific, please? At what line i should replace that?

**Comment by VladAdushev** [comment]
> > 
> 
> > > From the official huggingface repo's [issue](https://github.com/huggingface/accelerate/issues/1559):
> > > This is now project_dir (**not logging_dir**), and you should have been seeing warnings of it being deprecated for the last few accelerate versions.
> > 
> > 
> > thanks after i replace logging_dir by project_dir in file "train_dreambooth.py" ,it works
> 
> Thank you, @imccainiao. Im trying to replace logging_dir to project_dir and it doesnt work. Can you be more specific, please? At what line i should replace that?

Where did you find this line?

**Comment by NatalieHanzhina** [comment]
In[ this line](https://github.com/ShivamShrirao/diffusers/blob/main/examples/dreambooth/train_dreambooth.py#LL429C8-L429C8) change _logging_dir=logging_dir_ to _project_dir=logging_dir_

**Comment by VladAdushev** [comment]
I don't have many lines
!python3 train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_name_or_path="stabilityai/sd-vae-ft-mse" \
  --output_dir=$OUTPUT_DIR \
  --revision="fp16" \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --seed=1337 \
  --resolution=512 \
  --train_batch_size=1 \
  --train_text_encoder \
  --mixed_precision="fp16" \
  --use_8bit_adam \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=50 \
  --sample_batch_size=4 \
  --max_train_steps=800 \
  --save_interval=10000 \
  --save_sample_prompt="photo of zwx dog" \
  --concepts_list="concepts_list.json"

**Comment by VladAdushev** [comment]
you must edit the file "train_dreambooth.py".
Tell me how to edit it? Do it in the browser?

**Comment by imccainiao** [comment]
> you must edit the file "train_dreambooth.py". Tell me how to edit it? Do it in the browser?

i run this project in colab
then i download the file"train_dreambooth.py" and edit by notpad.exe
finally upload it to the colab again

**Comment by VladAdushev** [comment]
Thank you. Okay, I'll wait for Shivam Shrirao to fix it, I can't beat it.

**Comment by ShivamShrirao** [comment]
Merged https://github.com/ShivamShrirao/diffusers/pull/240

**Comment by SashaAlexandra22** [comment]
> In[ this line](https://github.com/ShivamShrirao/diffusers/blob/main/examples/dreambooth/train_dreambooth.py#LL429C8-L429C8) change _logging_dir=logging_dir_ to _project_dir=logging_dir_

Wooohoo! You saved our day, @ShivamShrirao and @NatalieHanzhina - i tried to replace that code, but it is already corrected! Thank you both!

**Comment by Hbhatt-merexgenAI** [comment]
TypeError: Accelerator.__init__() got an unexpected keyword argument 'project_dir'
