### ISSUE TITLE
Implementing AITemplate

### ISSUE THREAD

**Issue by x02Sylvie** [ShivamShrirao/diffusers#32]
Meta's AITemplate 0.1 released 6 hours ago

Supposedly AITemplate can speed up stable diffusion by up to 240%+ 
It could be worthwhile endeavour to get it working, especially if benefits can be stacked up along with xformers

![ait](https://user-images.githubusercontent.com/76458234/195099800-47c24ed6-f5d0-49ed-af1b-c58984c2da10.png)

https://github.com/facebookincubator/AITemplate/tree/main/examples/05_stable_diffusion

**Comment by ShivamShrirao** [comment]
It is just for inference so won't be helpful in training. I also tested it, it's good for inference but also takes a really long time to compile.

**Comment by 0xdevalias** [comment]
**See also:**

- https://github.com/facebookincubator/AITemplate/issues/102
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1625
- https://github.com/TheLastBen/fast-stable-diffusion/issues/73

**Comment by 0xdevalias** [comment]
> > It is just for inference so won't be helpful in training. I also tested it, it's good for inference but also takes a really long time to compile.
> 
> Just FYI - The compilation time with the latest open-source version has been improved a lot from our first release. In our experiences, it can be 4X faster for the models where computation-intensive ops are mostly GEMM-family ops. We've made similar improvement for Conv ops in our internal version, which will be sync-ed to the open-source repo later. Stay tuned. Thanks.
> 
> _Originally posted by @chenyang78 in https://github.com/facebookincubator/AITemplate/issues/102#issuecomment-1326014540_
