### ISSUE TITLE
caching latents doubt...

### ISSUE THREAD

**Issue by ZeroCool22** [ShivamShrirao/diffusers#35]
### Describe the bug

![Screenshot_3](https://user-images.githubusercontent.com/13344308/195586181-d0cab0c8-494f-471b-a597-567573b12d20.jpg)

I downloaded from a source 6650 img to use as classes, so not need to download it before training.

Now i see this **Caching Latents** eats a lot of VRAM, so what's the **max numbers** in **classes images folder** i can use to not run out of memory before the training start?

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
- Python version: 3.9.13
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.10.0
- Transformers version: 4.22.2
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by ShivamShrirao** [comment]
You can just disable caching latents if it's causing OOM.

**Comment by ZeroCool22** [comment]
> You can just disable caching latents if it's causing OOM.

Where i can disable it?

**Comment by VigneshBaskar** [comment]
> > You can just disable caching latents if it's causing OOM.
> 
> Where i can disable it?

You can pass the flag not_cache_latents True while running from the command line
