### ISSUE TITLE
How to use a custom initial model?

### ISSUE THREAD

**Issue by codestuff001** [ShivamShrirao/diffusers#37]
I tried replacing the "MODEL_NAME" in the "Settings and run" section with the path to my own chkpt file on google drive, but it doesn't seem to work. I can't seem to get it to work with anything other than the default "CompVis/stable-diffusion-v1-4"

Did I misunderstand or do something wrong?

**Comment by ShivamShrirao** [comment]
The ckpt needs to converted to diffusers version using this script first.
https://github.com/ShivamShrirao/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py
