### ISSUE TITLE
UnboundLocalError: local variable 'text_encoder' referenced before assignment | OSError: Error no file named model_index.json found 

### ISSUE THREAD

**Issue by jochemstoel** [ShivamShrirao/diffusers#44]
### Describe the bug

I've been using dreambooth training script for a while but all of a sudden I am getting this error _when the training is complete_.

> UnboundLocalError: local variable 'text_encoder' referenced before assignment

Since the training completed, I tried to run inference and it says:

> OSError: Error no file named model_index.json found 

### Reproduction

!wget -q https://github.com/ShivamShrirao/diffusers/raw/main/examples/dreambooth/train_dreambooth.py
%pip install -qq git+https://github.com/ShivamShrirao/diffusers
%pip install -q -U --pre triton
%pip install -q accelerate==0.12.0 transformers ftfy bitsandbytes gradio

%pip install -q https://github.com/metrolobo/xformers_wheels/releases/download/1d31a3ac_various_6/xformers-0.0.14.dev0-cp37-cp37m-linux_x86_64.whl

#@markdown Name/Path of the initial model.
MODEL_NAME = "/content/drive/MyDrive/stable_diffusion_weights/andrewjarvis5" #@param {type:"string"}

#@markdown Path for images of the concept for training.
INSTANCE_DIR = "/content/data/andrewjarvis" #@param {type:"string"}
!mkdir -p $INSTANCE_DIR

#@markdown A general name for class like dog for dog images.
CLASS_NAME = "image" #@param {type:"string"}
CLASS_DIR = f"/content/data/{CLASS_NAME}"

#@markdown If model weights should be saved directly in google drive (takes around 4-5 GB).
save_to_gdrive = True #@param {type:"boolean"}
if save_to_gdrive:
    from google.colab import drive
    drive.mount('/content/drive')

#@markdown Enter the directory name to save model at.

OUTPUT_DIR = "stable_diffusion_weights/andrewjarvis6" #@param {type:"string"}
if save_to_gdrive:
    OUTPUT_DIR = "/content/drive/MyDrive/" + OUTPUT_DIR
else:
    OUTPUT_DIR = "/content/" + OUTPUT_DIR

print(f"[*] Weights will be saved at {OUTPUT_DIR}")

!mkdir -p $OUTPUT_DIR

#@markdown sks is a rare identifier, feel free to replace it.

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="andrewjarvis {CLASS_NAME}" \
  --class_prompt="{CLASS_NAME}" \
  --seed=14100 \
  --resolution=512 \
  --train_batch_size=1 \
  --mixed_precision="fp16" \
  --use_8bit_adam \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=50 \
  --sample_batch_size=4 \
  --max_train_steps=3000

### Logs

```shell
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 112
CUDA SETUP: Loading binary /usr/local/lib/python3.7/dist-packages/bitsandbytes/libbitsandbytes_cuda112.so...
Caching latents: 100% 5563/5563 [19:19<00:00,  4.80it/s]
Steps: 100% 3000/3000 [46:10<00:00,  1.08it/s, loss=0.19, lr=5e-6]Traceback (most recent call last):
  File "train_dreambooth.py", line 688, in <module>
    main()
  File "train_dreambooth.py", line 676, in main
    text_encoder=accelerator.unwrap_model(text_encoder),
UnboundLocalError: local variable 'text_encoder' referenced before assignment
Steps: 100% 3000/3000 [46:10<00:00,  1.08it/s, loss=0.19, lr=5e-6]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=/content/drive/MyDrive/stable_diffusion_weights/andrewjarvis5', '--instance_data_dir=/content/data/andrewjarvis', '--class_data_dir=/content/data/image', '--output_dir=/content/drive/MyDrive/stable_diffusion_weights/andrewjarvis6', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=andrewjarvis image', '--class_prompt=image', '--seed=14100', '--resolution=512', '--train_batch_size=1', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--sample_batch_size=4', '--max_train_steps=3000']' returned non-zero exit status 1.


## After this error trying to run inference
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-bb26acbc4cb5> in <module>
      6 model_path = OUTPUT_DIR             # If you want to use previously trained model saved in gdrive, replace this with the full path of model in gdrive
      7 
----> 8 pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch.float16).to("cuda")
      9 g_cuda = None

1 frames
/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    216             else:
    217                 raise EnvironmentError(
--> 218                     f"Error no file named {cls.config_name} found in directory {pretrained_model_name_or_path}."
    219                 )
    220         else:

OSError: Error no file named model_index.json found in directory/content/drive/MyDrive/stable_diffusion_weights/andrewjarvis6.
```

### System Info

Google Colab Pro

**Comment by mustafakucuk0** [comment]
The code throws the same error in the local machine as well.

![image](https://user-images.githubusercontent.com/46380931/196748762-295b77bf-53de-42d3-823f-50bca71f514b.png)

**Comment by racecars** [comment]
same issue this afternoon -- have also been running in Google Colab Pro without issue for several days and just started getting this error

**Comment by racecars** [comment]
I think it has to do with some updates the owner made to train_dreambooth.py . If you're like me, and either saved a copy of the colab notebook to your drive and have been using that (or otherwise haven't refreshed the page) then you'd be missing the corresponding updates to the notebook, which I think is causing the issue. 

Adding:
 --train_text_encoder

as an argument to the accelerate command appears to have solved the issue for me

**Comment by ShivamShrirao** [comment]
Thanks, fixed in 45446addc38dac6e1b0d60554ceb16c5b7a1c69c

Btw check out the new colab with newer settings, it gives much better results by also training the text encoder.

**Comment by InB4DevOps** [comment]
> Thanks, fixed in [45446ad](https://github.com/ShivamShrirao/diffusers/commit/45446addc38dac6e1b0d60554ceb16c5b7a1c69c)
> 
> Btw check out the new colab with newer settings, it gives much better results by also training the text encoder.

Will text_encoder work with Colab free tier (since it only has 16GB VRAM)?

**Comment by ShivamShrirao** [comment]
@InB4DevOps Yes it works. It requires 13 GB VRAM.

**Comment by InB4DevOps** [comment]
> @InB4DevOps Yes it works. It requires 13 GB VRAM.

Nice! Then you might want to change the readme.md in examples/dreambooth where it says `Note: Training text encoder requires more memory, with this option the training won't fit on 16GB GPU. It needs at least 24GB VRAM.`

**Comment by ShivamShrirao** [comment]
Oh right, I didn't touch the readme in this fork.
