### ISSUE TITLE
Dreambooth colab - add option to reset cuda memory

### ISSUE THREAD

**Issue by jmp909** [ShivamShrirao/diffusers#45]
**Is your feature request related to a problem? Please describe.**
Sometimes retraining in the same session gives a CUDA memory allocation error

**Describe the solution you'd like**
suggest potentially adding this as an option to clear memory:
```
pip install numba
```
then
```python
from numba import cuda 
device = cuda.get_current_device()
device.reset()
```

worked for me!

thanks

**Comment by ShivamShrirao** [comment]
I was thinking of just doing
```
exit()
```
Does it work for you or cause any problems ?

**Comment by jmp909** [comment]
@ShivamShrirao which line are you putting the `exit()` on? also where would you re-run from?

normally I will just want to run the block to change the MODEL_NAME and OUTPUT_DIR then run the training again to create a an updated copy of the model
