### ISSUE TITLE
feature request: respect num_class_images when pointing to existing directory

### ISSUE THREAD

**Issue by codemonkeynorth** [ShivamShrirao/diffusers#49]
**Is your feature request related to a problem? Please describe.**
If I have a folder of say 1500 class image and I set `--num_class_images=500` it'll still cache all 1500

**Describe the solution you'd like**
would be useful if it just took the amount specified in `--num_class_images` (ie the first 500 out of 1500 in the case above)
potentially leave blank or use `-1` to specify "all in folder"

thanks

**Comment by ShivamShrirao** [comment]
added in 3e37579a82f252254d02bac403f8286f40860396
