### ISSUE TITLE
Support using new VAEs from Stability AI with Dreambooth

### ISSUE THREAD

**Issue by ProGamerGov** [ShivamShrirao/diffusers#55]
Stability AI recently released 2 new VAEs for Stable Diffusion v1.5, but they also work on 1.4 models:

* https://huggingface.co/stabilityai/sd-vae-ft-ema-original

* https://huggingface.co/stabilityai/sd-vae-ft-mse-original

They can greatly improve results, and thus I'd like to be able to use them with Dreambooth.

**Comment by ShivamShrirao** [comment]
I have added them, now sd-vae-ft-mse is on by default.

**Comment by ProGamerGov** [comment]
@ShivamShrirao Out of curiosity, why did you choose the MSE VAE as the default and not the other VAE?

**Comment by feffy380** [comment]
@ProGamerGov Based on the [model card](https://huggingface.co/stabilityai/sd-vae-ft-mse), it looks like MSE was trained longer overall (resumed from EMA) and the sample images show it's a bit better at reconstructing text and faces
