### ISSUE TITLE
Save checkpoint & preview every n steps

### ISSUE THREAD

**Issue by geocine** [ShivamShrirao/diffusers#58]
**Is your feature request related to a problem? Please describe.**
After training the model could be overfitting or underfitting, so I have to train again and reduce/increase steps. 

**Describe the solution you'd like**
If I have all the models on each step increment, then I can choose whatever is best.

**Describe alternatives you've considered**
I have to train again and reduce/increase steps.

**Additional context**
Please see https://github.com/TheLastBen/fast-stable-diffusion/issues/206 , https://github.com/DonStroganotti seem to have a solution at https://github.com/DonStroganotti/diffusers/blob/jocke_test/examples/dreambooth/train_dreambooth.py
https://github.com/TheLastBen/fast-stable-diffusion/issues/215

**Comment by ProGamerGov** [comment]
This Dreambooth implementation saves preview images every set number of iterations: https://github.com/JoePenna/Dreambooth-Stable-Diffusion

**Comment by 1blackbar** [comment]
Inference on top of trainin will up the RAM req i think? But yes iut would be very nice and maybe easy way to edit prompts for test images to test against certain styles

**Comment by ShivamShrirao** [comment]
Added in b3f97c032037a6aac6ef41b21f6f989c4376e6ee along with ability to save intermediate samples. You can refer to [colab](https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb) for more details.
