### ISSUE TITLE
New error: You have passed a non-standard module None. We cannot verify whether it has the correct type/15.

### ISSUE THREAD

**Issue by ZeroCool22** [ShivamShrirao/diffusers#70]
### Describe the bug

After the train ends, i got this error:

1 hour + wasted... :/

```
Caching latents: 100%|████████████████████████████████████████████████████████████████| 100/100 [00:25<00:00,  3.98it/s]Steps: : 3090it [1:31:46,  1.75s/it, loss=0.0682, lr=5e-6]Traceback (most recent call last):
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 213, in hf_raise_for_status
    response.raise_for_status()
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/diffusion_pytorch_model.bin

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/diffusers/modeling_utils.py", line 323, in from_pretrained
    model_file = hf_hub_download(
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1053, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1359, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 231, in hf_raise_for_status
    raise EntryNotFoundError(message, response) from e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error. (Request ID: HLPLwhninRbyKoTJt0Omq)

Entry Not Found for url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/diffusion_pytorch_model.bin.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 750, in <module>
    main()
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 744, in main
    save_weights(global_step)
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 632, in save_weights
    vae=AutoencoderKL.from_pretrained(args.pretrained_vae_name_or_path or args.pretrained_model_name_or_path, use_auth_token=True),
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/diffusers/modeling_utils.py", line 351, in from_pretrained
    raise EnvironmentError(
OSError: runwayml/stable-diffusion-v1-5 does not appear to have a file named diffusion_pytorch_model.bin.
Steps: : 3090it [1:31:48,  1.78s/it, loss=0.0682, lr=5e-6]
Traceback (most recent call last):
  File "/home/zerocool/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zerocool/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--instance_data_dir=training', '--class_data_dir=classes', '--output_dir=my_model', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=Stn6', '--class_prompt=man', '--resolution=512', '--train_batch_size=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--gradient_accumulation_steps=4', '--gradient_checkpointing', '--use_8bit_adam', '--max_train_steps=3000']' returned non-zero exit status 1.
(diffusers) zerocool@DESKTOP-IFR8E96:~/github/diffusers/examples/dreambooth$
```

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
- Python version: 3.9.13
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.10.0
- Transformers version: 4.22.2
- Using GPU in script?: 1080 TI
- Using distributed or parallel set-up in script?: <fill in>

**Comment by ZeroCool22** [comment]
![Screenshot_6](https://user-images.githubusercontent.com/13344308/197577821-f1ac86dd-d651-413c-9662-e85e99710bec.jpg)

I can see the file in the web....

**Comment by StNimmerlein** [comment]
The file in the web is in directory `unet`, the script is searching directly in the repos root. So there is some mismatch.
I'm running into the same error as well and did not yet get it fixed

**Comment by ZeroCool22** [comment]
> The file in the web is in directory `unet`, the script is searching directly in the repos root. So there is some mismatch. I'm running into the same error as well and did not yet get it fixed

Thx you very much to confirm this, i thought i was the only one getting this...

**Comment by StNimmerlein** [comment]
After adding `--pretrained_vae_name_or_path="stabilityai/sd-vae-ft-mse" \` to the parameters for the invocation of `train_dreambooth.py`, it made progress.
In the `launch.sh` this parameter was present, in the README it's missing so that's probably why we overlooked it.
Can you confirm whether it works now?

**Comment by ZeroCool22** [comment]
![Screenshot_10](https://user-images.githubusercontent.com/13344308/197601453-71809073-fc32-4761-a547-b1f21c2b64f6.jpg)

This how looks my train_dreambooth.py:

![Screenshot_10](https://user-images.githubusercontent.com/13344308/197601563-67dc6244-efd6-4284-84d1-4fa8bcb16919.jpg)

I added the arg you told me to my train.sh:

```
export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export INSTANCE_DIR="training"
export OUTPUT_DIR="my_model"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="SteveB" \
  --resolution=512 \
  --train_batch_size=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --gradient_accumulation_steps=4 --gradient_checkpointing \
  --use_8bit_adam \
  --max_train_steps=2500
```

With this should works now?

**Comment by StNimmerlein** [comment]
Just for clarification, `train_dreambooth.py` needs no modification.
You just add this parameter to your train.sh. However, I do not see it in the one you posted. It should look like this:
```
export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export INSTANCE_DIR="training"
export OUTPUT_DIR="my_model"

accelerate launch train_dreambooth.py \
  --pretrained_vae_name_or_path="stabilityai/sd-vae-ft-mse" \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="SteveB" \
  --resolution=512 \
  --train_batch_size=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --gradient_accumulation_steps=4 --gradient_checkpointing \
  --use_8bit_adam \
  --max_train_steps=2500
```

**Comment by ZeroCool22** [comment]
> Just for clarification, `train_dreambooth.py` needs no modification. You just add this parameter to your train.sh. However, I do not see it in the one you posted. It should look like this:
> 
> ```
> export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
> export MODEL_NAME="runwayml/stable-diffusion-v1-5"
> export INSTANCE_DIR="training"
> export OUTPUT_DIR="my_model"
> 
> accelerate launch train_dreambooth.py \
>   --pretrained_vae_name_or_path="stabilityai/sd-vae-ft-mse" \
>   --pretrained_model_name_or_path=$MODEL_NAME  \
>   --instance_data_dir=$INSTANCE_DIR \
>   --output_dir=$OUTPUT_DIR \
>   --instance_prompt="SteveB" \
>   --resolution=512 \
>   --train_batch_size=1 \
>   --learning_rate=5e-6 \
>   --lr_scheduler="constant" \
>   --lr_warmup_steps=0 \
>   --gradient_accumulation_steps=4 --gradient_checkpointing \
>   --use_8bit_adam \
>   --max_train_steps=2500
> ```

Yeah, i forget to added, i will try now with low steps to see if this works.

Thx!

**Comment by ZeroCool22** [comment]
> Just for clarification, `train_dreambooth.py` needs no modification. You just add this parameter to your train.sh. However, I do not see it in the one you posted. It should look like this:
> 
> ```
> export LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
> export MODEL_NAME="runwayml/stable-diffusion-v1-5"
> export INSTANCE_DIR="training"
> export OUTPUT_DIR="my_model"
> 
> accelerate launch train_dreambooth.py \
>   --pretrained_vae_name_or_path="stabilityai/sd-vae-ft-mse" \
>   --pretrained_model_name_or_path=$MODEL_NAME  \
>   --instance_data_dir=$INSTANCE_DIR \
>   --output_dir=$OUTPUT_DIR \
>   --instance_prompt="SteveB" \
>   --resolution=512 \
>   --train_batch_size=1 \
>   --learning_rate=5e-6 \
>   --lr_scheduler="constant" \
>   --lr_warmup_steps=0 \
>   --gradient_accumulation_steps=4 --gradient_checkpointing \
>   --use_8bit_adam \
>   --max_train_steps=2500
> ```

![Screenshot_11](https://user-images.githubusercontent.com/13344308/197607306-d01eced2-e5ba-4dbf-ae96-97d32199600b.jpg)

I get this now... :/
