### ISSUE TITLE
Can't run it on colab for some reason

### ISSUE THREAD

**Issue by leonnn1** [ShivamShrirao/diffusers#76]
### Describe the bug

I am getting these two errors 

 File "train_dreambooth.py", line 299, in __getitem__
    instance_path, instance_prompt = self.instance_images_path[index % self.num_instance_images]
ZeroDivisionError: integer division or modulo by zero

And 

 File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=/content/drive/MyDrive/stable_diffusion_weights/realigorlenC', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=202', '--sample_batch_size=4', '--max_train_steps=2021', '--save_interval=10000', '--save_sample_prompt=photo of realigorlenC dog', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.

I don't know why

### Logs

```shell
File "train_dreambooth.py", line 299, in __getitem__
    instance_path, instance_prompt = self.instance_images_path[index % self.num_instance_images]
ZeroDivisionError: integer division or modulo by zero




 File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=/content/drive/MyDrive/stable_diffusion_weights/realigorlenC', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=202', '--sample_batch_size=4', '--max_train_steps=2021', '--save_interval=10000', '--save_sample_prompt=photo of realigorlenC dog', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.
```

### System Info

Colab

**Comment by wistandbroshow** [comment]
same here

**Comment by ShivamShrirao** [comment]
You did not upload instance images

**Comment by blackmagic24** [comment]
For me broken after the commit "For me defective after the commit" (locally, not colab)
Caching latents: 100%|██████████| 126/126 ...
The 126 cached images are my instance images.

**Comment by ShivamShrirao** [comment]
@blackmagic24 what's the error ?

In this issue the op hadn't uploaded instance images.

**Comment by blackmagic24** [comment]
After the last "git pull" I can not reproduce the error.
Excuse me, maybe I'm wrong but haven't the regulation images been cached so far? In my case there were over 1500 images.
Thanks for your work!

**Comment by leonnn1** [comment]
I guess am not sure but I think that the issue was that there was a typo on my code, there was that part with a wrong name on mine, I changed it and it worked.
![image](https://user-images.githubusercontent.com/85142472/197713392-a7359e72-4ee7-42b8-8cff-e1058cd24e91.png)
