### ISSUE TITLE
Train imagic with custom CKPT

### ISSUE THREAD

**Issue by loboere** [ShivamShrirao/diffusers#84]
I am using the imagic colab, I could add the option to use a custom CKPT, train a dreambooth and use the script to generate the CKPT, I want to use this CKPT to train imagic.
it seems that the colab only uses the sd1-4.CKPT

**Comment by ShivamShrirao** [comment]
You can convert the ckpt to diffusers format using https://github.com/ShivamShrirao/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py
Then provide that path in MODEL_NAME
