### ISSUE TITLE
Feature Request: option to provide specific steps to save, or alternatively "start at"

### ISSUE THREAD

**Issue by jmp909** [ShivamShrirao/diffusers#85]
the `--save_interval` is really useful but likely we don't want to save the first few rounds

eg with `--save-interval=400` and `--max_train_steps=2000` it is likely I would want to save 800,1200,1600,2000 but not 400

therefore it would be useful to have at least one of the following options eg

A) `--first_save=400` (start at a specified interval)

or

B) `--save_interval=800,1200,1600` (if a comma list then use specific steps rather than every N. we would assume the last step (2000 in this example) will save automatically and doesn't need listing

or some similar implementation that would achieve the same thing

thanks
J

**Comment by ShivamShrirao** [comment]
Use `--save_min_steps`

**Comment by jmp909** [comment]
@ShivamShrirao I noticed it does not save at points expected.

if i set:
--save_interval=500
--save_min_steps=900
--max_train_steps=2400

there are checkpoints at 1000, 1500 and 2000

it should be 900, 1400, 1900

thanks

**Comment by ShivamShrirao** [comment]
Yeah, it is known. Haven't got time to set correctly yet. For now u can do save_min_steps=899
